name:       generative-art
version:    0.1.0.0
github:     quchen/generative-art
license:    BSD3
author:
    - David »quchen« Luposchainsky – dluposchainsky (λ) gmail
    - Franz Thoma – f.m.thoma (λ) gmail
copyright:
    - 2018–2022 David Luposchainsky
    - 2018–2022 Franz Thoma

extra-source-files:
    - README.md

description: Generative art using Haskell. See README.md.

dependencies:
    - base >= 4.7 && < 5

    - alfred-margaret
    - cairo
    - colour
    - containers
    - data-default-class
    - deepseq
    - directory
    - dlist
    - filepath
    - formatting
    - heaps
    - megaparsec
    - mtl
    - mwc-random
    - Noise
    - optparse-applicative
    - parallel
    - plotfont
    - primitive
    - random
    - regex-tdfa
    - text
    - tf-random
    - transformers
    - vector
    - vector-algorithms

default-extensions:
    - BangPatterns
    - LambdaCase
    - MultiWayIf
    - RecordWildCards

extra-doc-files:
    - docs/bezier/**/*.svg
    - docs/billard/**/*.svg
    - docs/colors/schemes/continuous/**/*.png
    - docs/colors/schemes/discrete/**/*.svg
    - docs/differential_equations/**/*.svg
    - docs/font/**/*.svg
    - docs/geometry/**/*.svg
    - docs/haddock/**/*.svg
    - docs/hexagonal/**/*.svg
    - docs/interpolation/**/*.svg
    - docs/iso_lines/**/*.svg
    - docs/penrose/**/*.svg
    - docs/physics/**/*.svg
    - docs/plotting/**/*.svg
    - docs/sampling/**/*.svg
    - docs/triangulation/**/*.svg

ghc-options:
    - -Wall
    - -Wno-type-defaults
    - -j
    - -Wno-incomplete-uni-patterns

library:
    source-dirs: src
    other-modules:
        - Draw.Color.Schemes.Internal.ColorBrewer2
        - Draw.Color.Schemes.Internal.Common
        - Draw.Color.Schemes.Internal.Haskell
        - Draw.Color.Schemes.Internal.MatPlotLib
        - Draw.Color.Schemes.Internal.Seaborn
        - Geometry.Algorithms.Clipping.CohenSutherland
        - Geometry.Algorithms.Clipping.Internal
        - Geometry.Algorithms.Clipping.MargalitKnott
        - Geometry.Algorithms.Clipping.SutherlandHodgman
        - Geometry.Algorithms.Contour.Internal
        - Geometry.Algorithms.Delaunay.Internal.Delaunator.Api
        - Geometry.Algorithms.Delaunay.Internal.Delaunator.Raw
        - Geometry.Algorithms.Sampling.PoissonDisc
        - Geometry.Trajectory.PathSimplifier.Radial
        - Geometry.Trajectory.PathSimplifier.RamerDouglasPeucker
        - Geometry.Trajectory.PathSimplifier.VisvalingamWhyatt
        - Geometry.Trajectory.ReassembleLines

tests:
    testsuite:
        main:        Main.hs
        source-dirs: test/testsuite
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
            - -Wall
            - -j
            - -Wno-type-defaults
            - -Wno-incomplete-uni-patterns
        dependencies:
            - generative-art

            - async
            - cairo
            - process
            - QuickCheck
            - random
            - tasty
            - tasty-hunit
            - tasty-quickcheck
            - transformers
            - directory
            - text
            - Glob

    doctest:
        main:        Main.hs
        source-dirs: test/doctest
        ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N, -Wall, -Wno-type-defaults]
        dependencies:
            - doctest
