flags: {}
packages:
    - .

    - app/voronoi_interactive

    - penplotting/ApollonianGasket
    - penplotting/circuits
    - penplotting/FlowLines
    - penplotting/Hatched
    - penplotting/Kilometer
    - penplotting/PenChangeCalibration
    - penplotting/PoissonDisc
    - penplotting/Pressure
    - penplotting/SvgSource
    - penplotting/Truchet
    - penplotting/Voronoi

    - showcases/circuits
    - showcases/haskell_logo_billard
    - showcases/haskell_logo_shattered
    - showcases/haskell_logo_voronoi
    - showcases/particle_shooter
    - showcases/pulsar
    - showcases/truchet
    - showcases/truchetti
    - showcases/vector_fields
    - showcases/voronoi_3d

extra-deps:
    - cairo-0.13.8.1@sha256:1938aaeb5d3504678d995774dfe870f6b66cbd43d336b692fa8779b23b2b67a9,4075
    - gtk2hs-buildtools-0.13.8.2@sha256:01c4a6cc3679008bd4caec32b49843acb27a5f48ee2b22484218f097835548f6,5238
    - Noise-1.0.6@sha256:7eb0d021e334ca2341a9cb51eac7d6f2c76b4e4e1a27264509b38264dc202b32,1994
    - data-r-tree-0.6.0@sha256:10a25ef70e6779c3bf5128cd45d033482a370ea07e92ab1c82678675de01d870,3668
    - plotfont-0.1.0.1@sha256:e3b2507c6350feee8ff5a612a0ac3f5a7e8f39efb2895fbca70c0220834652a4,1155
resolver: lts-18.19
