name:       wfc-profiling
version:    0.1.0.0
github:     quchen/generative-art
license:    BSD3
author:
    - Franz Thoma
copyright:
    - 2023 Franz Thoma

default-extensions:
    - LambdaCase
    - RecordWildCards

dependencies:
    - base
    - generative-art
    - cairo
    - multiset
    - mwc-random
    - vector

executables:
    wfc-profiling:
        main: Main.hs
        source-dirs: .
        ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N, -Wall, -Wno-type-defaults, -O]
