name:       hatched-blob
version:    0.1.0.0
github:     quchen/generative-art
license:    BSD3
author:
    - David Luposchainsky
copyright:
    - 2022 David Luposchainsky

dependencies:
    - generative-art
    - base
    - cairo
    - data-default-class
    - text
    - optparse-applicative
    - mwc-random

executables:
    hatched-blob:
        main: Main.hs
        source-dirs: .
        ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N, -Wall, -Wno-type-defaults, -O]
