name:       penplotting-metaballs
version:    0.1.0.0
github:     quchen/generative-art
license:    BSD3
author:
    - Franz Thoma
copyright:
    - 2022 Franz Thoma

default-extensions:
    - LambdaCase
    - OverloadedStrings
    - RecordWildCards

dependencies:
    - generative-art
    - base
    - cairo
    - data-default-class
    - mwc-random

executables:
    penplotting-metaballs:
        main: Main.hs
        source-dirs: .
        ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N, -Wall, -Wno-type-defaults, -O]
