name:       fabric
version:    0.1.0.0
github:     quchen/generative-art
license:    BSD3
author:     Franz Thoma
copyright:  "2023 Franz Thoma"

dependencies:
    - generative-art
    - base
    - cairo
    - mwc-random
    - multiset
    - vector

executables:
    fabric:
        main: Main.hs
        source-dirs: .
        ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N, -Wall, -Wno-type-defaults, -O]
